apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-deployment
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      app: kalavai-job-operator
  template:
    metadata:
      labels:
        app: kalavai-job-operator
    spec:
      serviceAccountName: {{ .Release.Name}}-sa
      containers:
        - name: operator
        {{ if .Values.image.tag }}
          image: "ghcr.io/kalavai-net/kalavai-job-operator:{{ .Values.image.tag }}"
        {{ else }}
          image: "ghcr.io/kalavai-net/kalavai-job-operator:{{ .Chart.Version }}"
        {{ end }}
          # Kopf command to run the script
          command: 
          - sh
          - -c
          - |
            kopf run /app/kalavai_job_operator/job_operator.py --verbose