image:
  tag: null # when null, this is set to match the chart version
  pullPolicy: IfNotPresent

operator:
  replicaCount: 1

jobTemplates:
  url: https://kalavai-net.github.io/kalavai-templates/
  interval: 10m
